spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        interceptor:
          classes: com.xl.kafka.interceptor.FirstProducerInterceptor,com.xl.kafka.interceptor.SecondProducerInterceptor

    consumer:
      group-id: myGroup
      enable-auto-commit: true
      auto-commit-interval: 100ms
      properties:
        interceptor:
          classes: com.xl.kafka.interceptor.MessageConsumerInterceptor,com.xl.kafka.interceptor.UserConsumerInterceptor
        session.timeout.ms: 15000
        spring:
          deserializer:
            value:
              delegate:
                class:  org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted: #这里的配置是告诉kafka，此包下的类都是可以信任的，否则kafkaConsumer在反序列化的时候会报The class *** is not in the trusted packages: [java.util, java.lang] 异常
              packages: "com.xl.kafka.*"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest